[print_schema]
file = "migrations/schema.rs"

[database]
# URL for the PostgreSQL database
url = "postgres://postgres:postgres@localhost:5432/my_database"

# Specify the path to the directory containing your migrations
migrations_directory = "migrations"

# Use the `postgres` feature for PostgreSQL support
# Replace with the appropriate feature for your database
features = ["postgres"]

# Connection pool configuration
# See https://docs.diesel.rs/diesel/connection/struct.ConnectionOptions.html for more options
[connection_options]
idle_timeout = 600

# Specify the default schema for your database
default_schema = "public"